// LOCALHOST
###
GET http://localhost:8080/read
###
POST http://localhost:8080/read HTTP/1.1
content-type: application/json

{
    "title": "Thinking with Type",
    "author": "Ellen Lupton",
    "copyrightDate": "2010"
}
###


// PRODUCTION Deploy
###
GET https://https://library-63wh.onrender.com/read
###
POST https://https://library-63wh.onrender.com/read HTTP/1.1
content-type: application/json

{
    "title": "Thinking with Type",
    "author": "Ellen Lupton",
    "copyrightDate": "2010"
}