# // LOCALHOST
# ###
# GET http://localhost:8080/contacts
# ###
# GET http://localhost:8080/contacts/63243351a3627fb019dda81b
# ###
# POST http://localhost:8080/contacts HTTP/1.1
# content-type: application/json

# {
#     "firstName": "Cristhian",
#     "lastName": "Matute",
#     "email": "cristhianm@test.com",
#     "favoriteColor": "Red",
#     "birthday": "08/18/1989"
# }
# ###
# PUT http://localhost:8080/contacts/63243351a3627fb019dda81c HTTP/1.1
# content-type: application/json

# {
#     "firstName": "Sammy",
#     "lastName": "Holt",
#     "email": "sammyj@test.com",
#     "favoriteColor": "Purple",
#     "birthday": "03/17/2019"
# }
# ###
# PUT http://localhost:8080/contacts/63243351a3627fb019dda81c HTTP/1.1
# content-type: application/json

# {
#     "firstName": "Sammy",
#     "lastName": "Holt",
#     "email": "sammyjean@test.com",
#     "favoriteColor": "Pink",
#     "birthday": "03/17/2019"
# }
# ###
# DELETE http://localhost:8080/contacts/632beecf58e027abc7313329 HTTP/1.1

// PRODUCTION Deploy
###
GET https://contacts-pf57.onrender.com/contacts
###
GET https://contacts-pf57.onrender.com/contacts/63243351a3627fb019dda81c
###
POST https://contacts-pf57.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Cristhian",
    "lastName": "Matute",
    "email": "cristhianm@test.com",
    "favoriteColor": "Red",
    "birthday": "08/18/1989"
}
###
PUT https://contacts-pf57.onrender.com/contacts/63243351a3627fb019dda81c HTTP/1.1
content-type: application/json

{
    "firstName": "Sammy",
    "lastName": "Holt",
    "email": "sammyj@test.com",
    "favoriteColor": "Purple",
    "birthday": "03/17/2019"
}
###
DELETE https://contacts-pf57.onrender.com/contacts/63243351a3627fb019dda81b HTTP/1.1